### ISSUE TITLE
add test cases

### ISSUE THREAD

**Issue by luizbarboza** [luizbarboza/polyclip-ts#1]
- [x] mfogel/polygon-clipping#75
- [x] mfogel/polygon-clipping#83
- [x] mfogel/polygon-clipping#86
- [x] mfogel/polygon-clipping#90
- [x] mfogel/polygon-clipping#91
- [x] mfogel/polygon-clipping#93
- [x] mfogel/polygon-clipping#94
- [x] mfogel/polygon-clipping#95
- [x] mfogel/polygon-clipping#96
- [x] mfogel/polygon-clipping#98
- [x] mfogel/polygon-clipping#101
- [x] mfogel/polygon-clipping#105
- [x] mfogel/polygon-clipping#111
- [x] mfogel/polygon-clipping#115
- [x] mfogel/polygon-clipping#118
- [x] mfogel/polygon-clipping#122
- [x] mfogel/polygon-clipping#124
- [x] mfogel/polygon-clipping#129
- [x] mfogel/polygon-clipping#139
- [x] mfogel/polygon-clipping#140
- [x] mfogel/polygon-clipping#141
- [x] mfogel/polygon-clipping#142

**Comment by Peque** [comment]
@SBanksX Did you run any performance tests after fixing all those floating point issues? I'd be interested in knowing how this implementation compares to https://github.com/mfogel/polygon-clipping.

Of course I can run the tests myself, but I am guessing there is a high chance you run them already while or after implementing the changes. :blush:

**Comment by shrinktofit** [comment]
Also provide a case similar to "Unable to complete output ring starting at...", your fork correctly processed this.  I posted the data here just for stub.

Reproduce step:
```js
// throws on polygon-clipping@0.15.7
clip.difference(geo1, geo2);
```

Geo1:
```json
[
  [
    [
      [
        -2,
        -1.8
      ],
      [
        -1.996157056080646,
        -1.8390180644032257
      ],
      [
        -1.9847759065022574,
        -1.876536686473018
      ],
      [
        -1.9662939224605092,
        -1.9111140466039205
      ],
      [
        -1.9414213562373095,
        -1.9414213562373097
      ],
      [
        -1.9111140466039205,
        -1.9662939224605092
      ],
      [
        -1.876536686473018,
        -1.9847759065022574
      ],
      [
        -1.8390180644032257,
        -1.996157056080646
      ],
      [
        -1.8,
        -2
      ],
      [
        -0.9822202400838272,
        -2
      ],
      [
        -1,
        -1.8194790681203206
      ],
      [
        -0.9917923830535696,
        -1.7361457347869873
      ],
      [
        -1,
        -1.652812401453654
      ],
      [
        -0.9917923830535696,
        -1.5694790681203206
      ],
      [
        -1,
        -1.4861457347869873
      ],
      [
        -0.9917923830535696,
        -1.402812401453654
      ],
      [
        -1,
        -1.3194790681203208
      ],
      [
        -0.9917923830535696,
        -1.2361457347869873
      ],
      [
        -1,
        -1.152812401453654
      ],
      [
        -0.9917923830535696,
        -1.0694790681203206
      ],
      [
        -1,
        -0.9861457347869874
      ],
      [
        -0.9807852804032304,
        -0.7910554127708588
      ],
      [
        -0.9238795325112867,
        -0.6034623024218975
      ],
      [
        -0.8314696123025453,
        -0.43057550176738524
      ],
      [
        -0.7071067811865475,
        -0.27903895360043984
      ],
      [
        -0.555570233019602,
        -0.15467612248444207
      ],
      [
        -0.3826834323650897,
        -0.06226620227570068
      ],
      [
        -0.1950903220161282,
        -0.005360454383756985
      ],
      [
        0,
        0.013854265213012584
      ],
      [
        0.19509032201612833,
        -0.005360454383756985
      ],
      [
        0.38268343236508984,
        -0.06226620227570068
      ],
      [
        0.5555702330196023,
        -0.15467612248444218
      ],
      [
        0.7071067811865476,
        -0.27903895360043995
      ],
      [
        0.8314696123025452,
        -0.43057550176738524
      ],
      [
        0.9238795325112867,
        -0.6034623024218977
      ],
      [
        0.9807852804032304,
        -0.7910554127708591
      ],
      [
        1,
        -0.9861457347869874
      ],
      [
        0.9917923830535696,
        -1.0694790681203206
      ],
      [
        1,
        -1.152812401453654
      ],
      [
        0.9917923830535696,
        -1.2361457347869873
      ],
      [
        1,
        -1.3194790681203208
      ],
      [
        0.9917923830535696,
        -1.402812401453654
      ],
      [
        1,
        -1.4861457347869873
      ],
      [
        0.9917923830535696,
        -1.5694790681203206
      ],
      [
        1,
        -1.652812401453654
      ],
      [
        0.9917923830535696,
        -1.7361457347869873
      ],
      [
        1,
        -1.8194790681203206
      ],
      [
        0.9822202400838272,
        -2
      ],
      [
        1.8,
        -2
      ],
      [
        1.8390180644032257,
        -1.996157056080646
      ],
      [
        1.876536686473018,
        -1.9847759065022574
      ],
      [
        1.9111140466039205,
        -1.9662939224605092
      ],
      [
        1.9414213562373095,
        -1.9414213562373097
      ],
      [
        1.9662939224605092,
        -1.9111140466039205
      ],
      [
        1.9847759065022574,
        -1.876536686473018
      ],
      [
        1.996157056080646,
        -1.8390180644032257
      ],
      [
        2,
        -1.8
      ],
      [
        2,
        1.8
      ],
      [
        1.996157056080646,
        1.8390180644032257
      ],
      [
        1.9847759065022574,
        1.876536686473018
      ],
      [
        1.9662939224605092,
        1.9111140466039205
      ],
      [
        1.9414213562373095,
        1.9414213562373095
      ],
      [
        1.9111140466039205,
        1.9662939224605092
      ],
      [
        1.876536686473018,
        1.9847759065022574
      ],
      [
        1.8390180644032257,
        1.996157056080646
      ],
      [
        1.8,
        2
      ],
      [
        -1.8,
        2
      ],
      [
        -1.8390180644032257,
        1.996157056080646
      ],
      [
        -1.876536686473018,
        1.9847759065022574
      ],
      [
        -1.9111140466039205,
        1.9662939224605092
      ],
      [
        -1.9414213562373095,
        1.9414213562373095
      ],
      [
        -1.9662939224605092,
        1.9111140466039205
      ],
      [
        -1.9847759065022574,
        1.876536686473018
      ],
      [
        -1.996157056080646,
        1.8390180644032257
      ],
      [
        -2,
        1.8
      ]
    ]
  ]
]
```

Geo2:

```json
[
  [
    [
      [
        1,
        -0.9861457347869873
      ],
      [
        0.9807852804032304,
        -0.7910554127708591
      ],
      [
        0.9238795325112867,
        -0.6034623024218975
      ],
      [
        0.8314696123025452,
        -0.4305755017673851
      ],
      [
        0.7071067811865476,
        -0.27903895360043984
      ],
      [
        0.5555702330196023,
        -0.15467612248444207
      ],
      [
        0.38268343236508984,
        -0.062266202275700566
      ],
      [
        0.19509032201612833,
        -0.005360454383756874
      ],
      [
        6.123233995736766e-17,
        0.013854265213012695
      ],
      [
        -0.1950903220161282,
        -0.005360454383756874
      ],
      [
        -0.3826834323650897,
        -0.062266202275700566
      ],
      [
        -0.555570233019602,
        -0.15467612248444196
      ],
      [
        -0.7071067811865475,
        -0.27903895360043973
      ],
      [
        -0.8314696123025453,
        -0.4305755017673851
      ],
      [
        -0.9238795325112867,
        -0.6034623024218975
      ],
      [
        -0.9807852804032304,
        -0.7910554127708587
      ],
      [
        -1,
        -0.9861457347869872
      ],
      [
        -0.9807852804032304,
        -1.1812360568031157
      ],
      [
        -0.9238795325112868,
        -1.368829167152077
      ],
      [
        -0.8314696123025455,
        -1.5417159678065893
      ],
      [
        -0.7071067811865477,
        -1.6932525159735348
      ],
      [
        -0.5555702330196022,
        -1.8176153470895327
      ],
      [
        -0.38268343236509034,
        -1.9100252672982738
      ],
      [
        -0.19509032201612866,
        -1.9669310151902177
      ],
      [
        -1.8369701987210297e-16,
        -1.9861457347869873
      ],
      [
        0.1950903220161283,
        -1.9669310151902177
      ],
      [
        0.38268343236509,
        -1.9100252672982738
      ],
      [
        0.5555702330196018,
        -1.8176153470895327
      ],
      [
        0.7071067811865474,
        -1.693252515973535
      ],
      [
        0.8314696123025452,
        -1.5417159678065895
      ],
      [
        0.9238795325112865,
        -1.3688291671520778
      ],
      [
        0.9807852804032303,
        -1.181236056803116
      ]
    ]
  ]
]
```
